### PR TITLE
Add support for running preprocessors before postcss

### LINKED ISSUE #18: Upgrading to 0.6.0 do not process .scss files anymore
After upgrading to `postcss-brunch` `0.6.0` my `.scss` files are no longer processed by `postcss`.

If I remame my `.scss` file to `.css` postcss properly processes my files.

### PR DESCRIPTION
**Pull request by lydell**
Fixes #18 (at least for me).

NOTE: If you want process regular .css files (not .scss or .less or whatever), don’t forget to install css-brunch.

### CODE REVIEW

**Comment by razor-x** [comment]
@paulmillr Ok, I'm a bit worried that this was merged. Yes it fixes the one issue, but it will break now for anyone who updated and started using this plugin as a compiler.

Is this plugin meant to be an optimizer or a compiler? It's gone optimizer -> compiler -> optimizer now. Things like modules with postcss-imports cannot be expected to work correctly now.

Let's find a stable solution 😄 

1) Do we need two plugins? postcss-brunch and postcss-brunch-optimize? css-brunch, sass-brunch and less-brunch are all compilers, so postcss-brunch should be a compiler IMO to stay consistent.
2) Can this plugin do both? Allow the config to support plugins to run for the compile step and plugins to run for the optimize step?

**Comment by lydell** [comment]
Yes, this is a breaking change. Why? Because people who only use postcss-brunch (not css-brunch, not sass-brunch etc.) won't get any CSS compiled at all.

There are two ways to go from there:
- Accept the breaking change, and release a new major version. Tell people to
  install css-brunch if needed.
- Add a "dummy" `compile()` and `extension: 'css'` in addition to `optimize()`.
  This way, css-brunch isn't needed, and the change is no longer breaking.

**However,** @razor-x mentions that there are other subtle, breaking changes because of the compiler → optimizer change. I don't know how that works. An example would be great!

> postcss-brunch should be a compiler IMO to stay consistent.

Here's my 2¢: Users don't care if a plugin is a compiler or an optimizer. They just want their stuff to work. In my opinion, it would be a downgrade user experience wise to force the user to make a choice between to plugins, or between two options of the same plugin. So I think postcss-brunch should _only_ be an optimizer, unless you can give some example where that wouldn't cover all cases. :)

**Comment by razor-x** [comment]
@lydell Thanks for the reply. I don't have time this morning to address each of your points, but I believe the main thing that will not work with this as an optimizer would be postcss-imports or module support.

**Comment by lydell** [comment]
> postcss-imports or module support

Looking forward to be enlightened on that topic :)

**Comment by razor-x** [comment]
@lydell Sure, I'm happy to go into detail when I have a bit more time, but the basic idea is that when making css modules, I have many css files I reference in JS. Those files (modules) may depend on postcss to generate the final set of class names, and if they have imports, postcss needs to include and process those files first as well. 

If postcss is an optimizer, then module generation cannot happen, as it will only operate on the concatenated file, which cannot be used to export proper modules. Also, even if not using modules, and only using postcss-import, references inside the concatenated  file will fail to resolve as they would refer to files under `app/assets` and not generated `public` assets.

Sorry if my explanation is too brief. A TLDR is: **postcss plugins now do things that Sass and Less do**, and those postcss plugins can not be used at the optimize step for the same reason Less and Sass cannot be used as optimizers.

While we work on the best way forward, @paulmillr: can we have a new release based on 29d990c7b6921295bd3e48536371abeab9604c64 so I and others can use this plugin with css-modules?

**Comment by lydell** [comment]
Ah, do optimizers operate on a _concatenated_ file? I had no idea.

Also, the example with broken relative paths is good.

What a mess.

**Comment by razor-x** [comment]
@lydell Yes, I believe that is the behaviour, but I may be mistaken. I think only compile supports exporting js modules, so even if that wasn't the case I'm not sure how to handle that with optimize, since the module would need to be generated by the last postcss plugin to run.

**Pull request merged**
