### PR TITLE
Add ignore option to postcss plugin

### PR DESCRIPTION
**Pull request by Zapix**
Hi I've got the same issue as #32. I think it'll be cool to use ignore option in plugin config.
Hope this PR will help you. 

Regards.

### CODE REVIEW

**Comment by shvaikalesh** [comment]
LGTM except for indent

**Comment by Zapix** [comment]
@shvaikalesh I've missed that you are using tab instead spaces. Updated PR.

**Comment by shvaikalesh** [comment]
@Zapix I would love to change that, but diff would be huge. Thanks.

**Comment by PoloGarcia** [comment]
When will this feature be available? 
I tried installing 2.0.6 but it says, it's not a valid installation target

**Pull request merged**
