### PR TITLE
Variables only files.

### PR DESCRIPTION
**Pull request by devel-pa**
Variables only files from LESS generates empty output that makes postcss crash.

### CODE REVIEW

**Comment by shvaikalesh** [comment]
I am not sure this should be handled on `postcss-brunch` side

**Comment by devel-pa** [comment]
I have no clear opinion, but as long as the input can be an empty file from whichever plugin runs previously, it might be the right place. You decide.

**Comment by devel-pa** [comment]
Probably it's not the time to merge. I'll do more research.

**Comment by shvaikalesh** [comment]
Does `postcss-brunch` from `master` work OK? (please, see https://github.com/brunch/postcss-brunch/pull/36)

**Comment by devel-pa** [comment]
No. 
less-brunch returns already an empty string for a file with variables.
Looks that poscss-brunch can't handle empty files that comes from above.

**Comment by devel-pa** [comment]
OK, make it work by sending the initial path from less-brunch to postcss-brunch and set it back to the file.path

Source maps still sucks

Something stinks with the new workflow

Update 1:

at least for LESS it is normal to have (in fact needed more than this)
```
opts.map.prev = file.map.toJSON ? file.map.toJSON() : file.map;
```
as long as LESS provides string source maps (which are not sent further, anyway, by less-brunch)


Update 2:

Downgrade to previous version (and without postcss) gives me the same result as the first sentence here. With postcss no sourcemaps.

**Comment by devel-pa** [comment]
I'll close this in favor of a new code proposal.

**Pull request closed without merging**
